"""
Django settings for home_lift project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from datetime import timedelta
import cloudinary
import stripe
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)


ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=lambda v: [s.strip() for s in v.split(",")]
)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    config('FRONTEND_URL') ,  
]
CSRF_TRUSTED_ORIGINS = [
    config('FRONTEND_URL'),  
]

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Only True if using HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'admins',
    'providers',
    'services',
    'bookings',
    'reviews',
    'payments',
    'core',
    'notifications',
    'wallet',
    'offers',
    'chat',
    
    'rest_framework',
    'corsheaders',
    'phonenumber_field',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'cloudinary',
    'cloudinary_storage',

    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# For using the abstract user model
AUTH_USER_MODEL = 'users.CustomUser'

ROOT_URLCONF = 'home_lift.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_lift.wsgi.application'
ASGI_APPLICATION = "home_lift.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Default page size for all list views
}


# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_USER_CLASS': 'users.CustomUser',
}


# Send OTP email settings 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


#Redis Cache settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL"), 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config("REDIS_URL")],
        },
    },
}

# File Upload Size Limits
MAX_IMAGE_SIZE_MB = 2  # 2 MB for images (profile pictures, icons, etc.)
MAX_DOCUMENT_SIZE_MB = 10  # 10 MB for documents (PDFs, verification docs)

# Django file upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15 MB max request size
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15 MB max file size

# Cloudinary settings (default file storage)
cloudinary.config( 
  cloud_name = config('CLOUDINARY_CLOUD_NAME'),
  api_key =  config('CLOUDINARY_API_KEY'),
  api_secret =  config('CLOUDINARY_API_SECRET'), 
  secure = True
)
DEFAULT_FILE_STORAGE = 'users.storage.NoDeleteCloudinaryStorage'
MEDIA_URL = '/media/'


# Stripe settings
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')

STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default=None)

# ─── Logging ───────────────────────────────────────────────────────────────────
# Logs directory: <project_root>/logs/  (created automatically if absent)
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}:{lineno} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {name} — {message}',
            'style': '{',
        },
    },

    'handlers': {
        # Console: INFO+ during development; swap to WARNING in production
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
        # Rotating file: WARNING+ always written to disk
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'homelift.log'),
            'maxBytes': 5 * 1024 * 1024,   # 5 MB per file
            'backupCount': 5,               # keep 5 rotated files
            'formatter': 'verbose',
            'level': 'WARNING',
            'encoding': 'utf-8',
        },
    },

    'loggers': {
        # Our project apps — DEBUG+ to console, WARNING+ to file
        'users':         {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'providers':     {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'bookings':      {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'chat':          {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'notifications': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'services':      {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'payments':      {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'wallet':        {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'admins':        {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'offers':        {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'core':          {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        # Django internals — WARNING+ only to avoid noise
        'django':        {'handlers': ['console', 'file'], 'level': 'WARNING', 'propagate': False},
        'django.request':{'handlers': ['console', 'file'], 'level': 'ERROR',   'propagate': False},
    },

    # Catch-all root logger
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
}
