# Generated by Django 5.2.4 on 2025-10-07 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture for the user', max_length=255, null=True, verbose_name='image'),
        ),
    ]
