# Generated by Django 5.2.4 on 2026-06-21 20:25

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture for the user (max 2 MB)', max_length=255, null=True, validators=[core.validators.validate_image_size], verbose_name='image'),
        ),
    ]
