# Generated by Django 5.2.4 on 2026-06-21 19:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('offers', '0001_initial'), ('offers', '0002_offer_category_offer_max_discount_offer_service'), ('offers', '0003_remove_offer_category')]

    initial = True

    dependencies = [
        ('services', '0004_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (useful for percentage discounts)', max_digits=10, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
