# Generated by Django 5.2.4 on 2026-02-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('services', '0004_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='services.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (useful for percentage discounts)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='services.service'),
        ),
    ]
