# Generated by Django 5.2.4 on 2026-03-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_category_offer_max_discount_offer_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
    ]
