# Generated by Django 5.2.4 on 2025-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
