# Generated by Django 5.2.4 on 2025-08-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
