# Generated by Django

from django.db import migrations, models
from django.db.models import Count

def merge_duplicate_chatrooms(apps, schema_editor):
    ChatRoom = apps.get_model('chat', 'ChatRoom')
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    
    # Identify unique pairs of (user, provider) that have more than one ChatRoom
    duplicates = ChatRoom.objects.values('user', 'provider').annotate(count=Count('id')).filter(count__gt=1)
    
    for dup in duplicates:
        user_id = dup['user']
        provider_id = dup['provider']
        
        # Get all rooms for this pair
        rooms = list(ChatRoom.objects.filter(user_id=user_id, provider_id=provider_id).order_by('created_at'))
        
        # Keep the oldest one
        main_room = rooms[0]
        other_rooms = rooms[1:]
        
        # Move all messages from other rooms to the main room
        for other_room in other_rooms:
            ChatMessage.objects.filter(room=other_room).update(room=main_room)
            other_room.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_chatrooms),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user', 'provider')},
        ),
    ]
