# Generated by Django 5.2.4 on 2025-08-13 15:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image or icon for this service', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image or icon for this category', max_length=255, null=True, verbose_name='image'),
        ),
    ]
