# Generated by Django 5.2.4 on 2025-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicecategory_image_service_icon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
    ]
