# Generated by Django 5.2.4 on 2026-06-21 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bookings', '0001_initial'), ('bookings', '0002_alter_booking_address'), ('bookings', '0003_booking_is_advance_paid'), ('bookings', '0004_booking_is_refunded'), ('bookings', '0005_booking_is_fully_paid'), ('bookings', '0006_remove_booking_is_fully_paid'), ('bookings', '0007_booking_is_provider_paid'), ('bookings', '0008_review'), ('bookings', '0009_booking_discount_amount_booking_original_price_and_more')]

    initial = True

    dependencies = [
        ('core', '0002_address_district'),
        ('services', '0004_alter_service_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.ForeignKey(blank=True, help_text='User’s saved address used for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.address')),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField(help_text='Date when the service is scheduled')),
                ('booking_time', models.TimeField(help_text='Time when the service should start')),
                ('price', models.DecimalField(decimal_places=2, help_text='Final price after discount', max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, help_text='Advance amount (2% of price, capped at ₹200, min ₹50)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Service provider assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('is_advance_paid', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False, help_text='Track if the advance has been refunded to wallet upon cancellation')),
                ('is_provider_paid', models.BooleanField(default=False, help_text='Track if the provider has been credited for this booking')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount deducted from original price via offers', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base service price before any discounts', max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
