# Generated by Django 5.2.4 on 2025-10-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0002_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, help_text='User’s saved address used for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.address'),
        ),
    ]
