# Generated by Django 5.2.4 on 2026-01-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_advance_paid',
            field=models.BooleanField(default=False),
        ),
    ]
