# Generated by Django 4.x on 2026-02-06
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='Track if the advance has been refunded to wallet upon cancellation'),
        ),
    ]
