# Generated by Django 5.2.4 on 2026-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
