# Generated by Django 5.2.4 on 2026-02-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_is_fully_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_fully_paid',
        ),
    ]
