# Generated by Django 5.2.4 on 2026-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_is_fully_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_provider_paid',
            field=models.BooleanField(default=False, help_text='Track if the provider has been credited for this booking'),
        ),
    ]
