# Generated by Django 5.2.4 on 2026-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount deducted from original price via offers', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base service price before any discounts', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Advance amount (2% of price, capped at ₹200, min ₹50)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Final price after discount', max_digits=10),
        ),
    ]
