# Generated by Django 5.2.4 on 2026-06-21 19:20

import cloudinary.models
import core.validators
import django.db.models.deletion
import providers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('providers', '0001_initial'), ('providers', '0002_providerdetails_is_active'), ('providers', '0003_providerservice'), ('providers', '0004_alter_providerdetails_status'), ('providers', '0005_alter_providerdetails_options_and_more'), ('providers', '0006_remove_providerdetails_document_and_more'), ('providers', '0007_providerapplication_document_type_and_more'), ('providers', '0008_rename_document_providerapplication_id_doc_and_more'), ('providers', '0009_remove_providerapplication_document_type'), ('providers', '0010_alter_providerapplicationservice_price'), ('providers', '0011_alter_providerapplication_id_doc'), ('providers', '0012_alter_providerapplication_id_doc_and_more'), ('providers', '0013_providerservicerequest'), ('providers', '0014_providerservicerequest_doc'), ('providers', '0015_providerdetails_stripe_account_id')]

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('services', '0003_rename_servicecategory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_details', to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_providers', to=settings.AUTH_USER_MODEL)),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connected Account ID for payouts', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Provider Detail',
                'verbose_name_plural': 'Provider Details',
            },
        ),
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', cloudinary.models.CloudinaryField(blank=True, help_text='Upload your verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='ID Document')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text="Only required if status is 'rejected'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_applications', to=settings.AUTH_USER_MODEL)),
                ('expiration_date', models.DateTimeField(default=providers.models.default_expiration, help_text='Temporary applications expire automatically')),
            ],
            options={
                'verbose_name': 'Provider Application',
                'verbose_name_plural': 'Provider Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', cloudinary.models.CloudinaryField(blank=True, help_text='Optional service verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='raw')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerapplication')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Provider Application Service',
                'verbose_name_plural': 'Provider Application Services',
                'unique_together': {('application', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='If left blank, defaults to service price', max_digits=10, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerdetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.service')),
                ('doc', cloudinary.models.CloudinaryField(blank=True, help_text='Optional service verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='raw')),
            ],
            options={
                'verbose_name': 'Provider Service',
                'verbose_name_plural': 'Provider Services',
                'unique_together': {('provider', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price requested by the provider (optional)', max_digits=10, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='providers.providerdetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_requests', to='services.service')),
                ('doc', cloudinary.models.CloudinaryField(blank=True, help_text='Optional service verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='raw')),
            ],
            options={
                'verbose_name': 'Provider Service Request',
                'verbose_name_plural': 'Provider Service Requests',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'service', 'status')},
            },
        ),
    ]
