# Generated by Django 5.2.4 on 2025-08-06 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerdetails_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerdetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Provider Detail', 'verbose_name_plural': 'Provider Details'},
        ),
        migrations.AddField(
            model_name='providerdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='providerdetails',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerdetails',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
