# Generated by Django 5.2.4 on 2025-08-13 15:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_providerdetails_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerdetails',
            name='document',
        ),
        migrations.RemoveField(
            model_name='providerdetails',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='providerdetails',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='providerdetails',
            name='status',
        ),
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', cloudinary.models.CloudinaryField(blank=True, help_text='Upload your verification document', max_length=255, null=True, verbose_name='raw')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text="Only required if status is 'rejected'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Application',
                'verbose_name_plural': 'Provider Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
