# Generated by Django 5.2.4 on 2025-09-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_remove_providerdetails_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License')], default='aadhaar', help_text='Select the type of document submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerdetails'),
        ),
    ]
