# Generated by Django 5.2.4 on 2025-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_rename_document_providerapplication_id_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='document_type',
        ),
    ]
