# Generated by Django 5.2.4 on 2025-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_remove_providerapplication_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplicationservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
