# Generated by Django 5.2.4 on 2025-09-17 00:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_alter_providerapplicationservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='id_doc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your verification document', max_length=255, null=True, verbose_name='ID Document'),
        ),
    ]
