# Generated by Django 5.2.4 on 2026-02-06 05:19

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_alter_providerapplication_id_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='id_doc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='ID Document'),
        ),
        migrations.AlterField(
            model_name='providerapplicationservice',
            name='id_doc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional service verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='doc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional service verification document (max 10 MB)', max_length=255, null=True, validators=[core.validators.validate_document_size], verbose_name='raw'),
        ),
    ]
