# Generated by Django 5.2.4 on 2026-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_providerservicerequest_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdetails',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connected Account ID for payouts', max_length=255, null=True),
        ),
    ]
