# Generated by Django 5.2.4 on 2025-10-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
    ]
